# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import litecnn.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=litecnn.models.upload_location)),
            ],
        ),
    ]
